CREATE TABLE LESSON (
  LESSON_ID INT PRIMARY KEY,
  LESSON_DISCIPLINE VARCHAR(128)  NOT NULL,
  LESSON_LESSONTYPE VARCHAR(128)  NOT NULL,
  AUDIENCE VARCHAR(128),
  LESSON_ADDRESS VARCHAR(128),
  LESSON_START VARCHAR(128)  NOT NULL);

